import os
import sys
from bson.objectid import ObjectId

# Adjust the paths for MacOS to get the flask_app directory
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Now you can import models from flask_app
from flask_app.config import db, client
from flask_app.models import GolferTournamentDetails

golfers_array = [
  "Keegan Bradley",
  "Jason Day",
  "Jason Dufner",
  "Pádraig Harrington",
  "Martin Kaymer",
  "Brooks Koepka",
  "Rory McIlroy",
  "Shaun Micheel",
  "Phil Mickelson",
  "Collin Morikawa",
  "Xander Schauffele",
  "Vijay Singh",
  "Justin Thomas",
  "Jimmy Walker",
  "Hideki Matsuyama",
  "Jon Rahm",
  "Scottie Scheffler",
  "Wyndham Clark",
  "Bryson DeChambeau",
  "Matt Fitzpatrick",
  "Brian Harman",
  "Shane Lowry",
  "Cameron Smith",
  "Viktor Hovland",
  "John Catlin",
  "Takumi Kanaya",
  "Daniel van Tonder",
  "Richard Bland",
  "Dean Burmester",
  "Thomas Detry",
  "Lee Hodges",
  "Viktor Hovland",
  "Robert MacIntyre",
  "Taylor Moore",
  "Alex Norén",
  "Justin Rose",
  "Sahith Theegala",
  "Brian Bergstol",
  "Brandon Bingaman",
  "Michael Block",
  "Andre Chi",
  "Tyler Collet",
  "Jess Droemer",
  "Bobby Gates",
  "Larkin Gross",
  "Justin Hicks",
  "Nic Ishee",
  "Tom Johnson",
  "Michael Kartrude",
  "Greg Koch",
  "Ryan Lenahan",
  "Dylan Newman",
  "John Somers",
  "Bob Sowards",
  "Eric Steiger",
  "Rupe Taylor",
  "Timothy Wiseman",
  "Ludvig Åberg",
  "An Byeong-hun",
  "Daniel Berger",
  "Christiaan Bezuidenhout",
  "Akshay Bhatia",
  "Jacob Bridgeman",
  "Sam Burns",
  "Patrick Cantlay",
  "Bud Cauley",
  "Eric Cole",
  "Corey Conners",
  "Cameron Davis",
  "Nick Dunlap",
  "Nico Echavarría",
  "Austin Eckroat",
  "Harris English",
  "Tony Finau",
  "Tommy Fleetwood",
  "Lucas Glover",
  "Max Greyserman",
  "Ben Griffin",
  "Adam Hadwin",
  "Harry Hall",
  "Russell Henley",
  "Joe Highsmith",
  "Tom Hoge",
  "Mackenzie Hughes",
  "Sungjae Im",
  "Stephan Jäger",
  "Michael Kim",
  "Kim Si Woo",
  "Tom Kim",
  "Min Woo Lee",
  "Denny McCarthy",
  "Matt McCarty",
  "Maverick McNealy",
  "Andrew Novak",
  "Taylor Pendrith",
  "J.T. Poston",
  "Séamus Power",
  "Aaron Rai",
  "Davis Riley",
  "Patrick Rodgers",
  "Adam Scott",
  "J.J. Spaun",
  "Jordan Spieth",
  "Sam Stevens",
  "Sepp Straka",
  "Nick Taylor",
  "Davis Thompson",
  "Jhonattan Vegas",
  "Kevin Yu",
  "Tyrrell Hatton",
  "Max Homa",
  "Nicolai Højgaard",
  "Brian Campbell",
  "Rafael Campos",
  "Garrick Higgo",
  "Patton Kizzire",
  "Karl Vilips",
  "Eugenio Chacarra",
  "Keita Nakajima",
  "Marco Penge",
  "Laurie Canter",
  "Luke Donald",
  "Rickie Fowler",
  "Sergio García",
  "Ryan Gerard",
  "Ryo Hisatsune",
  "Rasmus Højgaard",
  "Beau Hossler",
  "Dustin Johnson",
  "Johnny Keefer",
  "Chris Kirk",
  "Kurt Kitayama",
  "Jake Knapp",
  "Thriston Lawrence",
  "Justin Lower",
  "Max McGreevy",
  "Tom McKibbin",
  "Keith Mitchell",
  "Rasmus Neergaard-Petersen",
  "Joaquín Niemann"
];


for golfer in golfers_array:
    golfer_split_values = golfer.split(" ")
    first_name, last_name = golfer_split_values[0], ' '.join(golfer_split_values[1:])
    db_golfer = db.golfers.find_one({
        "FirstName": first_name, "LastName": last_name
    })

    golfer_tourney_details = GolferTournamentDetails(
        GolferId=db_golfer["_id"],
        Position=None,
        Name=db_golfer["FirstName"] + " " + db_golfer["LastName"],
        Score=0,
        R1=0,
        R2=0,
        R3=0,
        R4=0,
        Today=None,
        Thru=None,
        TotalStrokes=0,
        Earnings=None,
        FedexPts=None,
        TournamentId=ObjectId('6776ded5202130da68f72a2e'),
        Rounds=[],
        TeeTimes={},
        Cut=False,
        WD=False,
    )
    
    golfer_tourney_details.save()

    if not db_golfer:
        print(f"could not find {first_name} {last_name} in db")